version: "3"

services:
  agent:
    container_name: agent
    restart: always
    build: .
    networks:
      - calcNetworks
    ports:
      - 8888:8888
    command: [ "go", "run", "./cmd/agent/main.go" ]

  orchestrator:
    container_name: orchestrator
    restart: always
    build: .
    networks:
      - calcNetworks
    ports:
      - 9999:9999
      - 8080:8080
    command: [ "go", "run", "./cmd/orchestrator/main.go" ]

networks:
  calcNetworks:
    driver: bridge